---
title: "Shivani's Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows 
    vertical_layout: fill
    social: ["twitter","facebook","menu"]
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(ggvis)
```
```{r}
data<-read.csv("/Users/shivanisingh/Downloads/vehicle.csv")

```
```{r}
mycolors<-c("lavender","pink","#AFC","grey")
```
Interactive Dashboard
================================

ROW
--------------------------------

### Car Failure Analysis 

```{r}
valueBox(paste("failure"),
         color="warning")
```

### Car Failure In US 
```{r}
valueBox(length(data$State),
        icon="Fa-user")
```
### ** Labour Cost 
```{r}
gauge(round(mean(data$lc),
            digits=2),
            min= 0,
            max=350,
            gaugeSectors(success = c(0,150),
                         warning =c(150,240),
                         danger = c(240,350),
                         colors=c('green','yellow','red')))
```

### Massachusetts
```{r}
valueBox(sum(data$State=="MA"),
        icon="fa-building" )
```

### California 
```{r}
valueBox(sum(data$State=="CA"),
         icon="fa-building")
```
### Texas 
```{r}
valueBox(sum(data$State=="TX"),
         icon="fa-building")
```
### Florida 
```{r}
valueBox(sum(data$State=="FL"),
         icon="fa-building")
```

ROW
-------------------------------
### Failure By State 
```{r}
p1<-data %>%
  group_by(State) %>%
  summarise(count=n()) %>%
  plot_ly(x= ~State,
          y= ~count,
          color = rainbow(51),
          type='bar') %>%
layout(xaxis= list(title="Failures By State"),
yaxis = list(title='Count'))
p1
```

```{r}
p2<-data %>%
  group_by(State) %>%
  summarise(count = n()) %>%
  filter(count>50) %>%
  plot_ly(labels = ~State,
          values = ~ count,
          marker = list(colors = mycolors)) %>%
  add_pie(hole = 0.4) %>%
  layout(xaxis = list(zeroline = F ,
                      showline = F ,
                      showticklabels = F,
                      showgrid = F),
         yaxis = list(zeroline = F,
                      showline = F,
                      showticklabels = F,
                      showgrid = F))
p2
```
### Failure Month Vs Failure Mileage 

```{r}
p3<- plot_ly(data,
             x = ~fm,
             y = ~Mileage,
             text = paste("FM:",data$fm,
                          "Mileage:",
                          data$Mileage),
             type="bar") %>%
  layout(xaxis = list(title = "FM"),
         yaxis = list(title = "Failure Mileage"))
p3
```
Row
------------------------------------
### Scatter Plot of Month Vs Mileage 

```{r}
p4<- plot_ly(data, x=~fm) %>%
  add_markers(y = ~Mileage,
             text = ~paste("Mileage:",Mileage),
             showlegend = F) %>%
  add_lines(y = ~fitted(loess(Mileage ~ fm)),
             name = "Loess Smoother",
             color = I("#FFC125"),
             showlegend = T,
             line = list (width=5)) %>%
  layout(xasixs = list(title = "Month"),
         yaxis = list(title = "Mileage"))
p4
``` 

### Box Plot Of Top State

```{r}
data %>%
  group_by(State) %>%
  ggvis(~State,~lc,fill= ~State) %>%
  layer_boxplots()
```


Data Table 
===========================================
```{r}
datatable(data,
          caption = "Failure Data",
          rownames = T ,
          filter = "top",
          options = list(pagelength = 25))
```

Pivot Table 
============================================
```{r}
rpivotTable( data,
             aggregatorName = "Count",
             cols ="fm",
             rows = "State",
             rendererName = "Heatmap")
```

Summary Report {data-orientation = colums}
============================================
----------------------------------------------

Column{data-width = 100}
--------------------------------------------

### Max Failure Month

```{r}
valueBox(max(data$fm),
         icon = "fa-user")
```
### Average Labour Cost 
```{r}
valueBox(round(mean(data$lc),
               digits = 2),
               icon = "fa-area-chart")
```
### Average Mileage at Failure 
```{r}
valueBox(round(mean(data$Mileage),
               digits = 2),
         icon = "fa-area-chart")
```

Column 
-------------------------------------
Report 

* This is a report on `r length(data$fm)` car failure .

* The average labor cost was `r mean(data$lc)` .

* The average material cost was `r mean(data$mc)` . 
